version: "3.3"
services:
  server:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: "${NODE_ENV}"
    restart: unless-stopped
    command: npm start
    depends_on:
      - db

  db:
    container_name: mileagetracker_db
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

networks:
  default:
    external:
      name: mt_backend
volumes:
  postgres_data:
